# Customize the codemagic.yaml file according to your project and commit it to the root of your repository
# Check out https://docs.codemagic.io/getting-started/yaml/ for more information
workflows:
  spotify-workflow:
    name: Spotify Pipeline
    scripts:
      - name: CICD Started
        script: echo "Welcome to your CICD set up"
      - name: Build Spotify
        script: xcodebuild build -workspace "Spotify.xcworkspace" -scheme "Spotify" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    publishing:
      email:
        recipients:
          - hello@iosacademy.io
